name: Publish to npm

on:
  push:
    branches:
      - master # or your target branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Step 3: Install npm dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Configure npm to use the correct registry
      - name: Configure npm registry
        run: npm config set registry https://registry.npmjs.org/

      # Step 5: Run the build process (optional, if you have a build step)
      - name: Build the project
        run: npm run build

      # Step 6: Publish to npm
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Correctly referencing the NPM_TOKEN secret
